In [1]:
import numpy as np

In [2]:
# Creating array--
list1 = [1,2,3,4]
list1

[1, 2, 3, 4]

In [3]:
arr_lst1 = np.array(list1)
print(arr_lst1)
print(type(arr_lst1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
list1 = [4,5,6]
list2 = [1,2,3]
arr_lst = np.array([list1,list2])
print(arr_lst)

[[4 5 6]
 [1 2 3]]


In [5]:
lst1 = (1,2,3,4)
lst2 = (5,6,7,8)
lst3 = (8,9,11,22)
d3_array = np.array([[lst1,lst2,lst3]])
d3_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 8,  9, 11, 22]]])

In [6]:
# Numpy array Attributes---
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print("Shape" , arr1.shape)
print("Size" , arr1.size)
print("data-type",arr1.dtype)
print("Dimention",arr1.ndim)

Shape (2, 3)
Size 6
data-type int64
Dimention 2


In [8]:
# Array Initilization Methods--
# Zeros array methods--
zero_arr = np.zeros((2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
one_arr = np.ones((1,2,3))
one_arr

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
full_Arr = np.full((3,2),9)
full_Arr

array([[9, 9],
       [9, 9],
       [9, 9]])

In [11]:
# Identity Matrix--Alwayse square matrixs
id_arr = np.eye(3)
id_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Empty Array--
print(np.empty(2))


[1.08364e-318 0.00000e+000]


In [13]:
# Evenly Spaces Array--
print(np.arange(1,10,2))

[1 3 5 7 9]


In [14]:
# Specific number Values of equallt spaces b/w range--
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [15]:
# Random values array-- Float
random_arr = np.random.rand(3,2)
random_arr

array([[0.80416006, 0.51398835],
       [0.24424246, 0.13388227],
       [0.48592117, 0.22962667]])

In [16]:
# Random values array-- Integer
r_arr = np.random.randint(1,100,(3,3))
r_arr

array([[75, 49, 20],
       [67, 41, 66],
       [ 9, 59, 85]])

In [17]:
# Array indexing and Slicing--
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [18]:
# Indexing--
print(a[0])
print(a[1])
print(a[4])

1
2
5


In [19]:
# Slicing--
# array = [Start:end:step]
print(a[0:3])

[1 2 3]


In [20]:
# For last 3 Elements--
print(a[-3:])

[3 4 5]


In [21]:
print(a[1:5:2])

[2 4]


In [22]:
print(a[0::])

[1 2 3 4 5]


In [23]:
dim2_arr = np.array([[1,2,3],[4,5,6]])
dim2_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
print(dim2_arr[0][0])
print(dim2_arr[1][0])

1
4


In [25]:
print(dim2_arr[1])
print(dim2_arr[1:])

[4 5 6]
[[4 5 6]]


In [26]:
print(dim2_arr[:,0])
print(dim2_arr[:,1])
print(dim2_arr[:,2])

[1 4]
[2 5]
[3 6]


In [27]:
arr3 = ([[1,2,3],[4,5,6],[6,7,8]])
print(arr3)

[[1, 2, 3], [4, 5, 6], [6, 7, 8]]


In [28]:
print(arr3[0][1])
print(arr3[2][2])

2
8


In [29]:
np_arr = np.d3_array(1,2,3)

AttributeError: module 'numpy' has no attribute 'd3_array'