In [1]:
import numpy as np

In [2]:
# Creating array--
list1 = [1,2,3,4]
list1

[1, 2, 3, 4]

In [5]:
arr_lst1 = np.array(list1)
print(arr_lst1)
print(type(arr_lst1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
list1 = [4,5,6]
list2 = [1,2,3]
arr_lst = np.array([list1,list2])
print(arr_lst)

[[4 5 6]
 [1 2 3]]


In [11]:
lst1 = (1,2,3,4)
lst2 = (5,6,7,8)
lst3 = (8,9,11,22)
d3_array = np.array([[lst1,lst2,lst3]])
d3_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 8,  9, 11, 22]]])